# Site settings
title: Maxime Sahroui - Freelance JavaScript Developer
description: > # this means to ignore newlines until "baseurl:"
  I'm a freelance JavaScript developer from Belgium. I like : JavaScript, Node.js, AngularJS, Meteor, startup world, growth hacking and agile methodologies.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://maximesahroui.be" # the base hostname & protocol for your site
available: true

# Build settings
markdown: kramdown
